language: perl
perl:
  - "5.20"
before_install:
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps | cpanm --quiet --notest
install:
  - dzil listdeps | cpanm --quiet --notest
script:
  - dzil test
